language: c
os:
    - linux
    - osx

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
compiler:
    - gcc
    - clang

env:
    global:
        # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
        #   via the "travis encrypt" command using the project repo's public key
        #- secure: ""

addons:
  coverity_scan:
    project:
      name: "xmidt-org/ultri1"
      description: "A powerful C based trie library."
    notification_email: weston_schmidt@alumni.purdue.edu
    build_command_prepend: "mkdir coverity_build && cd coverity_build && cmake .."
    build_command: "make"
    branch_pattern: master

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install codecov; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install cunit md5sha1sum; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y -qq libcunit1 libcunit1-dev lcov valgrind; fi

install:

script:
    - mkdir build
    - cd build
    - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then cmake .. -DDISABLE_VALGRIND:BOOL=true; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake ..; fi
    - make
    - make test

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then codecov; fi
